name: Auto Rollback Azurerm Version

on:
  workflow_dispatch:  # Trigger manually

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find the previous commit where azurerm version was updated
        id: find_previous_commit
        run: |
          # Initialize variables
          prev_commit=""
          prev_version=""
          
          # Loop through the commit history until we find a commit with an azurerm version change
          for commit in $(git log --reverse --grep='azurerm' --format='%H'); do
            echo "Checking commit: $commit"
            
            # Checkout each commit
            git checkout $commit
            
            # Get the azurerm version from the current commit
            current_version=$(grep 'version = "~>' main.tf | sed 's/.*~> \(.*\)"/\1/')
            
            if [ "$current_version" != "$prev_version" ]; then
              prev_commit=$commit
              prev_version=$current_version
              break
            fi
          done
          
          echo "Previous commit with azurerm version change: $prev_commit"
          echo "Previous azurerm version: $prev_version"
          
          # Set the commit and version for later steps
          echo "::set-output name=prev_commit::$prev_commit"
          echo "::set-output name=prev_version::$prev_version"

      - name: Checkout the previous commit
        run: |
          git checkout ${{ steps.find_previous_commit.outputs.prev_commit }}

      - name: Revert to the previous azurerm version
        run: |
          # Update main.tf with the previous version of azurerm
          sed -i 's/version = "~> .*/version = "~> ${{ steps.find_previous_commit.outputs.prev_version }}"/' main.tf

      - name: Check if changes were made
        id: check_changes
        run: |
          git diff --exit-code || echo "Changes detected in main.tf"
          
      - name: Commit and Push the changes if any
        if: steps.check_changes.outputs.exit_code != 0
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Commit the reverted version
          git add main.tf
          git commit -m "Revert azurerm version to ${{ steps.find_previous_commit.outputs.prev_version }}"
          
          # Push changes back to the repository
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main



# name: Manual Rollback Azurerm Version

# on:
#   workflow_dispatch:
#     inputs:
#       previous_version:
#         description: 'Enter the previous azurerm version to revert to'
#         required: true
#         type: string

# jobs:
#   rollback:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Revert azurerm version
#         run: |
#           # Modify main.tf to revert azurerm version
#           echo "Reverting azurerm version to ${{ github.event.inputs.previous_version }}"
          
#           # Use sed to find the version line in main.tf and replace it with the provided version
#           sed -i 's/version = "~> .*/version = "~> ${{ github.event.inputs.previous_version }}"/' main.tf

#       - name: Commit changes
#         run: |
#           git config --global user.name "GitHub Actions"
#           git config --global user.email "actions@github.com"
          
#           # Commit the change
#           git add main.tf
#           git commit -m "Revert azurerm version to ${{ github.event.inputs.previous_version }}"
          
#           # Push changes using GITHUB_TOKEN for authentication
#           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
